filebeat.inputs:
  - type: container
    paths:
      - /var/log/containers/*.log
    symlinks: true
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after

output.kafka:
  hosts: ["localhost:9092"]
  topic: "logs"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
